language: python
python:
  - "2.6"
  - "2.7"
# python3 version is tested on `python3` branch
install:
  - pip install -r requirements.txt --use-mirrors
before_script: ./run.sh &
after_script: pkill -9 -f "run.sh"
script: ./test.sh