language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
install:
  - pip install -r requirements.txt --use-mirrors
before_script: python src/hello.py &
after_script: pkill -9 -f "hello.py"
script: nosetests